### ISSUE TITLE
screencapture

### ISSUE THREAD

**Issue by paulirish** [gyazo/Gyazo#6]
the GyazoGIF stuff is fantastic, but it doesn't seem to be part of this repo.
are you willing to opensource the video capture?

**Comment by uiureo** [comment]
@paulirish 
Hi, I'm a developer of Gyazo GIF.
Well, we cannot opensource it for now because of business reasons. But I wanna create the opensourced version of it someday.

Do you want to host images on your own servers?

**Comment by paulirish** [comment]
> Hi, I'm a developer of Gyazo GIF.

Awesome. nice to meet you. thanks for commenting. :)

> Well, we cannot opensource it for now because of business reasons. But I wanna create the opensourced version of it someday.

I understand. :) To be honest I was surprised to see so much of gyazo is still available as open-source. 

> Do you want to host the images on your own servers?

Yes that is the goal. 

Many years ago I [got excited about gyazo](http://www.paulirish.com/2009/get-gyazo-for-seriously-instant-screen-grabbing/) and soon after that started hosting on my own server.

I've [recently been thinking about](https://github.com/h5bp/lazyweb-requests/issues/170) the new ideal for screenshot/screencapture and it's a step beyond what everyone has right now. 

But regardless, i've been enjoying Gyazo GIF. Very easy and straightforward to use. :)

**Comment by uiureo** [comment]
Your idea sounds nice. Better video screencapture would be great. maybe I can help.

**Comment by SnowGabe** [comment]
Is Gyazo still open source? When does the program show advertisements?

**Comment by uiureo** [comment]
@SnowGabe 
> Is Gyazo still open source?

Yes. The code on github is licensed under GPL.

There is also the hosted version, gyazo.com . Technically, the app on gyazo.com is a little bit different from the open-sourced version. But the basic feature is same.

> When does the program show advertisements?

The open-sourced version does not show any ads.
